COMMON_CFLAGS= -c -Wall -D__LITTLE_ENDIAN__

ifeq ($(findstring i86Linux2.6gcc,$(EPROSIMA_TARGET)), i86Linux2.6gcc)
	COMMON_CFLAGS+= -m32 -fpic
	LDFLAGS=-m32
endif
ifeq ($(findstring x64Linux2.6gcc,$(EPROSIMA_TARGET)), x64Linux2.6gcc)
	COMMON_CFLAGS+= -m64 -fpic
	LDFLAGS=-m64
endif

CFLAGS = $(COMMON_CFLAGS) -O2
CFLAGS_DEBUG= $(COMMON_CFLAGS) -g

TARGET= $(EPROSIMA_TARGET)

INCLUDE_DIRS=

LIBRARY_PATH=
JAVA_LIBRARY_PATH=
LIBS=
LIBS_CPP= $(LIBS)
LIBS_JAVA= $(LIBS)
LIBS_DEBUG=
LIBS_CPP_DEBUG= $(LIBS_DEBUG)
LIBS_JAVA_DEBUG= $(LIBS_DEBUG)

